name: mr_code_jr
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^1.3.0
  provider: ^5.0.0
  easy_localization: ^3.0.0
  flutter_bloc: ^7.0.1
  cloud_firestore: ^2.2.2
  flutter:
    sdk: flutter
  slider_button: ^0.6.0
  flutter_swipable: ^0.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/app_icon.png"
    image_path_android: "assets/images/app_icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ISAR_GAMES_LOGO.jpeg
    - assets/images/isar_logo_siyah.png
    - assets/images/gamezone.png
    - assets/images/İsarSoft.png
    - assets/images/isar_logo_1.png
    - assets/images/level1.png
    - assets/images/level2.png
    - assets/images/level3.png
    - assets/images/level4.png
    - assets/images/level5.png
    - assets/images/level6.png
    - assets/images/level7.png
    - assets/images/level8.png
    - assets/images/level9.png
    - assets/images/level10.png
    - assets/images/level11.png
    - assets/images/level12.png
    - assets/images/level13.png
    - assets/images/level14.png
    - assets/images/level15.png
    - assets/images/level16.png
    - assets/images/level17.png
    - assets/images/level18.png
    - assets/images/level19.png
    - assets/images/level20.png
    - assets/images/level21.png
    - assets/images/level22.png
    - assets/images/level23.png
    - assets/images/level24.png
    - assets/images/level25.png
    - assets/images/level26.png
    - assets/images/level27.png
    - assets/images/level28.png
    - assets/images/level29.png
    - assets/images/level30.png
    - assets/images/swipedImage.png
    - assets/images/cardLevelImage1.png
    - assets/images/cardLevelImage2.png
    - assets/images/cardLevelImage3.png
    - assets/images/cardLevelImage4.png
    - assets/images/cardLevelImage5.png
    - assets/images/cardLevelImage6.png
    - assets/images/cardLevelImage7.png
    - assets/images/cardLevelImage8.png
    - assets/images/cardLevelImage9.png
    - assets/images/cardLevelImage10.png
    - assets/images/cardLevelImage11.png
    - assets/images/cardLevelImage12.png
    - assets/images/cardLevelImage13.png
    - assets/images/cardLevelImage14.png
    - assets/images/cardLevelImage15.png
    - assets/images/cardLevelImage16.png
    - assets/images/cardLevelImage17.png
    - assets/images/cardLevelImage18.png
    - assets/images/cardLevelImage19.png
    - assets/images/cardLevelImage20.png
    - assets/images/cardLevelImage21.png
    - assets/images/cardLevelImage22.png
    - assets/images/cardLevelImage23.png
    - assets/images/cardLevelImage24.png
    - assets/images/cardLevelImage25.png
    - assets/images/cardLevelImage26.png
    - assets/images/cardLevelImage27.png
    - assets/images/cardLevelImage28.png
    - assets/images/cardLevelImage29.png
    - assets/images/cardLevelImage30.png
    - assets/images/commingSoon.png

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
